// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpWgP8oTw-FqLsKS6Jm0rsq_JnswFcWb4',
    appId: '1:971906820653:web:46934f617748d675aa26a4',
    messagingSenderId: '971906820653',
    projectId: 'global-text-reader',
    authDomain: 'global-text-reader.firebaseapp.com',
    storageBucket: 'global-text-reader.firebasestorage.app',
    measurementId: 'G-Z7DK3HZKC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBceoHSHpX0_hRCrGk38VZ1XUaJEd6U_ew',
    appId: '1:971906820653:android:a1b50ec21019c6d3aa26a4',
    messagingSenderId: '971906820653',
    projectId: 'global-text-reader',
    storageBucket: 'global-text-reader.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGb5x677ffqQZvZ33uWRPGh1gpA0086dY',
    appId: '1:971906820653:ios:d08912237fdf18b5aa26a4',
    messagingSenderId: '971906820653',
    projectId: 'global-text-reader',
    storageBucket: 'global-text-reader.firebasestorage.app',
    iosBundleId: 'com.example.globalTextReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGb5x677ffqQZvZ33uWRPGh1gpA0086dY',
    appId: '1:971906820653:ios:d08912237fdf18b5aa26a4',
    messagingSenderId: '971906820653',
    projectId: 'global-text-reader',
    storageBucket: 'global-text-reader.firebasestorage.app',
    iosBundleId: 'com.example.globalTextReader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpWgP8oTw-FqLsKS6Jm0rsq_JnswFcWb4',
    appId: '1:971906820653:web:00667a2523c7a15baa26a4',
    messagingSenderId: '971906820653',
    projectId: 'global-text-reader',
    authDomain: 'global-text-reader.firebaseapp.com',
    storageBucket: 'global-text-reader.firebasestorage.app',
    measurementId: 'G-KCBWB434R2',
  );
}
